### ISSUE TITLE
Просьба проверить домашнее задание

### ISSUE THREAD

**Issue by suberg** [suberg/typing-practice#1]
@JSMonk https://github.com/JSMonk/typing-practice/compare/homework-task...suberg:homework-task-solution

**Comment by JSMonk** [comment]
Здравствуйте, Антон.

Ну [Клиент тоже](https://github.com/JSMonk/typing-practice/compare/homework-task...suberg:homework-task-solution#diff-5ce32ffc3fa5f5c14a82c78d7749131fb692d127a4838d043c65b760cec5dee0R4) может залогиниться, только не имеет доступ к `Dashboard`.

А все остальное очень даже хорошо 👍

**Comment by suberg** [comment]
Добрый день, Артём!
Изменил название типа на PriviligedUser.

**Comment by JSMonk** [comment]
Доброе время, Антон.
Дело не столько в названии, сколько в самой возможности логина.
Вот [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...suberg:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR11) Вы запрещаете клиенту логиниться.

**Comment by suberg** [comment]
@JSMonk Не совсем понимаю, куда может залогиниться тогда клиент, если Dashboard имеет корневой урл (localhost:3000/) и других страниц в принципе нет. Или же просто у клиента должна отсутствовать возможность менять роли пользователей, но при этом он будет видеть дашборд?

**Comment by JSMonk** [comment]
Представьте, что это лишь маленькая часть приложения.
Например, когда Вы логинетесь в Telegram, для админов групп и каналов показывается другой интерфейс, нежели простым пользователям, а страница изменения настроек этих каналов недоступна пользователю вовсе.

**Comment by suberg** [comment]
Спасибо за пояснение! Клиент теперь может залогиниться, но дашборд ему недоступен.

**Comment by JSMonk** [comment]
Все супер.
Задание принято.
Хорошая работа 👍
